version: '3'

services:

  # PHP
  php:
    # Dockerfile内にFROMとして記載
    # image: php:7.4-fpm
    container_name: php
    # Dockerfile内のコマンドを実行させたいときはbuld指定をする（context:とdockerfile:でパスとファイル名を別々で指定できる様子）
    build: ./_docker/php
    depends_on:
    - db
    volumes:
    - ./public:/var/www/html
    - ./_docker/php/php.ini:/usr/local/etc/php/php.ini

  # nginx
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
    - php
    ports:
    - 8080:80
    volumes:
    - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./public:/var/www/html
    - ./public:/usr/share/nginx/html

  # mysql
  db:
    image: mysql
    # container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
    #   TZ: 'Asia/Tokyo'
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
    volumes:
    - ./_docker/db/data:/var/lib/mysql
    - ./_docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    # SQLファイルの実行（test_tableを作成しその中にいくつかデータを登録）
    - ./_docker/db/sql:/docker-entrypoint-initdb.d

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # container_name: phpmyadmin
    depends_on:
    - db
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db
    - PMA_USER=docker_user
    - PMA_PASSWORD=docker_pass
    ports:
    - 3000:80
    volumes:
    - ./_docker/phpmyadmin/sessions:/sessions
